#@formatter:off
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "{{ .Chart.Name }}.fullname" . }}
{{ include "{{ .Chart.Name }}.labels" . | indent 2 }}
data:
{{ tpl ((.Files.Glob "configs/*").AsConfig) . | indent 2 }}